=== Nusiq/bedrock-objects-definitions/models_schema/root.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Bedrock Object Definition",
    "description": "Definition of an object used in Minecraft Bedrock Edition behavior- and resource- pack",
    "type": "object",
    "properties": {
        "multi": {
            "type": "boolean",
            "description": "Whether the file can define multiple objects."
        },
        "type": {
            "enum": ["JSON", "other"],
            "description": "The type of a file 'JSON' or 'other'."
        },
        "pack_type": {
            "enum": ["behavior-pack", "resource-pack"],
            "description": "The type of the pack that owns this object."
        },
        "path": {
            "type": "array",
            "items": {
                "type": "string"
            },
            "description": "The list of glob patterns relative to the file path of the pack that contains this object."
        },
        "json_path": {
            "$ref": "json_path.json",
            "description": "Path to the outermost piece of data about the object inside its JSON file."
        },
        "identifier": {
            "$ref": "identifier.json",
            "description": "Describes how to get the identifier of the object from the file."
        },
        "properties": {
            "type": "object",
            "additionalProperties": {
                "$ref": "property.json",
                "description": "Describes how to get a property of the object from the file."
            },
            "not": {"required": ["identifier"]}
        },
        "$schema": {}
    },
    "required": [
        "multi", "type", "pack_type", "path", "identifier",
        "properties"
    ],
    "additionalProperties": false
}

=== Nusiq/bedrock-objects-definitions/models/client_entity.json
{
	"$schema": "../models_schema/root.json",
	"type": "JSON",
	"multi": false,
	"path": ["RP/entity/**/*.json"],
	"json_path": [],
	"pack_type": "resource-pack",
	"identifier":  {
		"json-path-value": {
			"path": ["minecraft:client_entity", "description", "identifier"],
			"path_start": "file"
		}
	},
	"properties": {
		"particle_effects": {
			"alias_mapping": {
				"referenced_object": "particle",
				"access_paths": [
					{
						"multi": true,
						"path_start": "object",
						"path": ["minecraft:client_entity", "description", "particle_effects", "@STR"]
					}
				]
			}
		},
		"particle_emitters": {
			"alias_mapping": {
				"referenced_object": "particle",
				"access_paths": [
					{
						"multi": true,
						"path_start": "object",
						"path": ["minecraft:client_entity", "description", "particle_emitters", "@STR"]
					}
				]
			}
		},
		"sound_effects": {
			"alias_mapping": {
				"referenced_object": "sound_definition",
				"access_paths": [
					{
						"multi": true,
						"path_start": "object",
						"path": ["minecraft:client_entity", "description", "sound_effect", "@STR"]
					}
				]
			}
		},
		"animations": {
			"alias_mapping": {
				"referenced_object": "client_animation",
				"access_paths": [
					{
						"multi": true,
						"value_processing": {
							"filters": {
								"exclude": false,
								"items": [{"starts_with": "animation."}]
							}
						},
						"path_start": "object",
						"path": ["minecraft:client_entity", "description", "animations", "@STR"]
					}
				]
			}
		},
		"animation_controllers": {
			"alias_mapping": {
				"referenced_object": "client_animation_controller",
				"access_paths": [
					{
						"multi": true,
						"value_processing": {
							"filters": {
								"exclude": false,
								"items": [{"starts_with": "controller.animation."}]
							}
						},
						"path_start": "object",
						"path": ["minecraft:client_entity", "description", "animations"]
					}
				]
			}
		}
	}
}

=== Nusiq/bedrock-objects-definitions/models/particle.json
{
	"$schema": "../models_schema/root.json",
	"type": "JSON",
	"multi": false,
	"json_path": [],
	"pack_type": "resource-pack",
	"path": ["RP/particles/**/*.json"],
	"identifier": {
		"json-path-value": {
			"path": ["particle_effect", "description","identifier"],
			"path_start": "file",
			"processing": {}
		}
	},
	"properties": {}
}

=== Nusiq/bedrock-objects-definitions/models/client_animation.json
{
	"$schema": "../models_schema/root.json",
	"type": "JSON",
	"multi": true,
	"pack_type": "resource-pack",
	"path": ["RP/animations/**/*.json"],
	"json_path": ["animations", "@STR"],
	"identifier": {
		"json-path-key": {
			"path": [],
			"path_start": "object",
			"processing": {
				"filters": {
					"exclude": false,
					"items": ["test", {"starts_with": "animation."}]
				}
			}
		}
	},
	"properties": {
		"particle_effect": [
			{
				"json_path_value": {
					"type": {
						"alias_reference": {
							"map_path": ["particle_effects"],
							"map_provider": "client_entity"
						}
					},
					"multi": true,
					"path_start": "object",
					"path": ["particle_effects", "@STR", "@SKIP_LIST", "effect"],
					"expected_types": ["string"],
					"processing": {
						"expected_types": ["string"]
					}
				}
			}
		],
		"sound_effect": [
			{
				"json_path_value": {
					"type": {
						"alias_reference": {
							"map_path": ["sound_effects"],
							"map_provider": "client_entity"
						}
					},
					"multi": true,
					"path_start": "object",
					"path": ["sound_effects", "@STR", "@SKIP_LIST", "effect"],
					"expected_types": ["string"]
				}
			}
		]
	}
}

=== Nusiq/bedrock-objects-definitions/models/animation.json
{
	"$schema": "../models_schema/root.json",
	"pack_type": "behavior-pack",
	"type": "JSON",
	"multi": true,
	"path": [
		"BP/animations/**/*.json"
	],
	"json_path": ["animations", "@STR"],
	"identifier": {
		"json-path-key": {
			"path": [],
			"path_start": "object",
			"processing": {
				"filters": {
					"exclude": false,
					"items": ["test", {"starts_with": "animation."}]
				}
			}
		}
	},
	"properties": {
		"function": {
			"json_path_value": {
				"multi": true,
				"type": "reference",
				"path_start": "object",
				"path": ["timeline", "@STR", "@STR"],
				"processing": {
					"postprocessing": [
						{
							"regex_replace": {
								"case_sensitive": true,
								"full_match": true,
								"match": "/function (\\w|\\/)+$",
								"out": "$1"
							}
						}
					]
				}
			}
		}
	}
}

=== Nusiq/bedrock-objects-definitions/models/client_animation_controller.json
{
	"$schema": "../models_schema/root.json",
	"pack_type": "resource-pack",
	"type": "JSON",
	"multi": true,
	"path": ["RP/animation_controllers/**/*.json"],
	"json_path": ["animation_controllers", "@STR"],
	"identifier": {
		"json-path-key": {
			"path_start": "object",
			"path": [],
			"processing": {
				"filters": {
					"exclude": false,
					"items": ["test", {"starts_with": "animation.controller."}]
				}
			}
		}
	},
	"properties": {
		"state": [{
			"json_path_key": {
				"type": {"custom": {}},
				"multi": true,
				"path_start": "object",
				"path": ["animation_controllers", "@STR", "states"],
				"expected_types": ["object"],
				"subproperties": {
					"animation": [
						{
							"json_path_value": {
								"multi": true,
								"type": {
									"alias_reference": {
										"map_provider": "client_entity",
										"map_path": ["animations"]
									}
								},
								"path_start": "object",
								"path": ["animations", "@INT"],
								"expected_types": ["string"]
							}
						},
						{
							"json_path_key": {
								"multi": true,
								"type": {
									"alias_reference": {
										"map_provider": "client_entity",
										"map_path": ["animations"]
									}
								},
								"path_start": "object",
								"path": ["animations", "@INT", "@STR"],
								"expected_types": ["string"]
							}
						}
					],
					"particle_effect": [{
						"json_path_value": {
							"multi": true,
							"type": {
								"alias_reference": {
									"map_provider": "client_entity",
									"map_path": ["particle_effects"]
								}
							},
							"path_start": "object",
							"path": ["particle_effects", "@INT", "effect"],
							"expected_types": ["string"]
						}
					}],
					"sound_effect": [{
						"json_path_value": {
							"multi": true,
							"type": {
								"alias_reference": {
									"map_provider": "client_entity",
									"map_path": ["sound_effects"]
								}
							},
							"path_start": "object",
							"path": ["sound_effects", "@INT", "effect"],
							"expected_types": ["string"]
						}
					}]
				}
			}
		}]
	}
}

=== Nusiq/bedrock-objects-definitions/models/sound_definition.json
{
	"$schema": "../models_schema/root.json",
	"type": "JSON",
	"multi": true,
	"pack_type": "resource-pack",
	"path": ["RP/sounds/sound_definitions.json"],
	"json_path": ["sound_definitions", "@STR"],
	"identifier": {
		"json-path-key": {
			"path_start": "object",
			"path": [],
			"processing": {}
		}
	},
	"properties": {}
}
